#!/bin/sh

IPADDR=192.168.254.7
WIDTH=16
GATEWAY=192.168.10.1

echo "Mounting Procfs..."

mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys

echo "Initializing Network..."

# Setup loopback
ip link set lo up

# Setup eth0
ip link set eth0 up
ip addr add $IPADDR/$WIDTH dev eth0
ip route add default via $GATEWAY dev eth0

echo "Entering Shell..."

mount /dev/vda root
chroot root
